### PR TITLE
bib: Add the ICC 2020 paper

### PR DESCRIPTION
**Pull request by dcallega**
Added paper to required places in the website and to the author's pages.
PDF included.

### CODE REVIEW

**Comment by igorburago** [comment]
LGTM, but let me think a bit more about having full abstracts within
BibTeX entries. Originally, the idea was that abstracts or, even better,
detailed summaries of papers would go into separate pages under
`content/publications/` (which, if present, are automatically linked
from all generated bibliographies—we just do not have any of those
created yet, but the automatic linking mechanism is already there).

**Comment by igorburago** [comment]
By the way, I have added the missing reference to the new paper into
the bibliography on Marco’s personal page (which should generally
mirror the global bibliography on the Publications page).

**Comment by dcallega** [comment]
Great! Thanks!

**Comment by igorburago** [comment]
I was still doing some experiments to see how expensive it would be
for us to have abstracts right within bibliography entries (what we do
for one paper we will—and should, generally—do for all papers).
I would have merged it in as is (i.e., with the abstract field), anyway,
but still. I was going to explain this after the Friday’s meeting, but
my attention was carried away by other issues.

On the one hand, I’m still slightly uneasy with having full abstracts
in BibTeX, because instinctively I strive to minimize the size of the
BibTeX entries, as it directly affects the size of the Publications
page (and all other pages with bibliographies). We do not put all the
BibTeX fields into visible text on the page, but the BibTeX snippets
that we generate for each entry are a part of the page (albeit
invisible by default), and therefore do increase its weight.

On the other hand, having abstract right next to an entry on the
Publications page would be nice. However, if we start adding abstracts
directly to entries, we should (in order of importance):

1. Keep adding abstracts to all *future* BibTeX entries.
2. Add a button in the row of “extras”—those links and buttons
accompanying each generated bibliography entry—to open up and
show the text of the abstract whenever available (in the same fashion
it is done for the BibTeX snippet).
3. Eventually add abstracts to as many *existing* BibTeX entries
as possible.

Let us think about this cost-benefit tradeoff for a few more days.
Currently, I am in favor of adding the abstracts, but only slightly,
with the aforementioned reservations. If we assume that the tradeoff
is worth it, I will do task 2 from above and will be ensuring that
task 1 is done for every new entry being added from here on.
Task 3 is challenging, though, because it cannot be automated easily
and also because we need the LaTeX *source* of abstracts, not their
rendered text version.

**Pull request merged**
